language: node_js

node_js:
  - "5.8"

sudo: false

branches:
  only:
    - master
    - /^feature\/.*$/

script:
  - npm install
  - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
